# Generated by Django 6.0.4 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(
                choices=[
                    ('action', 'Action'),
                    ('comedy', 'Comedy'),
                    ('drama', 'Drama'),
                    ('documentary', 'Documentary'),
                    ('horror', 'Horror'),
                    ('romance', 'Romance'),
                    ('sci-fi', 'Sci-Fi'),
                    ('thriller', 'Thriller'),
                    ('animation', 'Animation'),
                    ('sport', 'Sport'),
                ],
                max_length=100,
            ),
        ),
    ]
